### ISSUE TITLE
T1137.006 multi errors

### ISSUE THREAD

**Issue by frack113** [redcanaryco/atomic-red-team#1700]
## What did you do?
![image](https://user-images.githubusercontent.com/62423083/147599895-8edbf34c-6e11-43ea-a363-df5bd6f3a094.png)

## What did you change?
fix the `https://https://github.com` 
```yml
xll_url:
      description: url of the file HelloWorldXll.xll
      type: Url
      default: 'https://github.com/redcanaryco/atomic-red-team/tree/master/atomics/T1137.006/bin/HelloWorldXll.xll?raw=true'
```
but 
![image](https://user-images.githubusercontent.com/62423083/147600351-b44609bb-5c9e-4044-b5b8-5d21dd3ae5c1.png)
