### ISSUE TITLE
Idea: Detection Criteria

### ISSUE THREAD

**Issue by packetzero** [redcanaryco/atomic-red-team#2170]
### Use-cases
I would like to automate AtomicRedTeam testing to make sure software releases are catching known techniques.  It's easy to automate running of the tests, but there's not enough detail to validate that telemetry contains all the expected techniques.

### Proposal

Take `T1222.002` for example.  There are `process` events, but there are also specific `file` events.  The `Chown through c script` test in particular runs a compiled c program, and just having `process` events won't tell you much.

For each test, we need to specify `detection` criteria.  See the reference below for an example.  It will take a while to add detections for enough tests to make it worthwhile, and I am willing to work on it with my team.  The test `atomics/T1543.001/T1543.001.yaml` would have it's corresponding sigma rules in `detect_rules/T1543.001/T1543.001.sigma.yml`.

What schema should used?
  - It might be easiest to leverage [sigma yaml rules](https://github.com/SigmaHQ/sigma)

How can users map the generic schema to their own specific telemetry?
  - They will need to augment their rule engine to read their telemetry and map schema

How can users use the detection files?
 - They will need a sigma engine.  I did a POC using https://github.com/markuskont/go-sigma-rule-engine , and the one thing it is missing for me is the specific detection names that match (e.g. `process_launchctl`).  I don't think it would be hard to add.

There are multiple tests for each technique.  How do we specify which test the detection refers to?
 - I guess we need to specify the test name.  If the test gets renamed, that will break detection linkage.

### References
Here is an example of a rule for `T1543.001`
```yaml
title: Create or Modify System Process Launch Agent
id: T1543.001
test_name: Launch Agent
description: Utilize LaunchAgent to make file in tmp
source_commands:
  - if [ ! -d ~/Library/LaunchAgents ]; then mkdir ~/Library/LaunchAgents; fi;
  - sudo cp #{path_malicious_plist} ~/Library/LaunchAgents/#{plist_filename}
  - sudo launchctl load -w ~/Library/LaunchAgents/#{plist_filename}
detection:
  process_cp:
    EventType: exec
    ExecutablePath: '/bin/cp'
    CommandLine|contains:
      - 'atomicredteam_T1543_001.plist'
      - '~/Library/LaunchAgents'

  process_launchctl:
    EventType: exec
    ExecutablePath: '/bin/launchctl'
    CommandLine|contains:
      - 'com.atomicredteam.plist'

  process_touch:
    EventType: exec
    ExecutablePath: '/usr/bin/touch'
    CommandLine|contains:
      - '/tmp/T1543_001_atomicredteam.txt'

  file_create:
    EventType: create
    TargetPath|contains: '/private/tmp/T1543_001_atomicredteam.txt'
    
  condition: 1 of process* OR 1 of file*
```
