### ISSUE TITLE
yaml files pass a dict to the command instead of component of the dict

### ISSUE THREAD

**Issue by carnal0wnage** [redcanaryco/atomic-red-team#276]
Example: T1002
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1002/T1002.yaml

input arguments are:
```
input_arguments:
    input_file:
      description: Path that should be compressed into our output file
      type: Path
      default: C:\*
```
the input_file variable then contains the following based on parsing the yaml:
`{'description': 'Path that should be compressed into our output file', 'type': 'Path', 'default': 'C:\\*'}`

command then takes:

```
executor:
    name: powershell
    command: |
      dir #{input_file} -Recurse | Compress-Archive -DestinationPath #{output_file}
```

thus you are passing a dict to the command part 

i assume it should be something like #{input_file.default} or #{input_file['default']}   whatever makes sense here
