### ISSUE TITLE
Problem: Missing prereq and get_prereq from T1531-6

### ISSUE THREAD

**Issue by alvinnieto** [redcanaryco/atomic-red-team#3106]
## What did you do?

Run pwsh on mac for the test case "Delete User via sysadminctl utility"
Invoke-AtomicTest T1531-6

## What did you expect to happen?

I am expecting that a get_prereq command will prepare/add the default account first, before attempting to perform deletion

## What happened instead?

No account deletion happened since the account to be deleted did not exist in the first place

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)? Mac OS 14 M2
* Did you run the test from an elevated or root prompt? Yes
* If relevant, which atomic test is this specific to? T1531-6

Expected change is to add prereq and get_prereq under dependencies (fix is from LLM)
```
- name: Delete User via sysadminctl utility
  description: |
    This test deletes the user account using the sysadminctl utility.
  supported_platforms:
    - macos
  executor:
    name: sh
    elevation_required: true
  input_arguments:
    user_account:
      description: User account which will be deleted.
      type: string
      default: ARTUserAccount
    user_name:
      description: New user name.
      type: string
      default: ARTUser
    user_password:
      description: New user password.
      type: string
      default: ARTPassword
  attack_commands:
    - sysadminctl -deleteUser #{user_account}
  cleanup_commands:
    - sysadminctl -addUser #{user_account} -fullName "#{user_name}" -password #{user_password}
  dependencies:
    - description: Ensure the user account exists before deletion.
      prereq_command: |
        id -u #{user_account}
      get_prereq_command: |
        sysadminctl -addUser #{user_account} -fullName "#{user_name}" -password #{user_password}
```
