### ISSUE TITLE
Inconsistencies In Variable Names

### ISSUE THREAD

**Issue by caseysmithrc** [redcanaryco/atomic-red-team#317]
The Following Techniques Need to Be Corrected.
1042
1053
1065
1075
1103
1124
1191

There are inconsistencies in the input_arguments and the command property.

Example:  T1042
```
---
attack_technique: T1042
display_name: Change Default File Association

atomic_tests:
- name: Change Default File Association
  description: |
    Change Default File Association From cmd.exe

  supported_platforms:
    - windows
  input_arguments:
    extension_to_change:
      description: File Extension To Hijack
      type: String
      default: .wav
    target_exenstion_handler:   <<<<<<<< THIS SHOULD MATCH 
      description: Thing To Open
      type: Path
      default: C:\Program Files\Windows Media Player\wmplayer.exe
  executor:
    name: command_prompt
    command: |
      cmd.exe assoc #{extension_to_change}="#{thing_to_execute}"  <<<<<< THIS 

```
target_extension_handler s/b renamed to thing_to_execute Or vice versa 

My recommendation is once we fix these that the validation routine be updated to check this.
