### ISSUE TITLE
PowerShell Executor doesn't work in Python Execution Framework in Win7

### ISSUE THREAD

**Issue by sisoma2** [redcanaryco/atomic-red-team#509]
# Report

## What did you do?
Modified[ Atomic Test #5 - Windows - Modify file creation timestamp with PowerShell](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1099/T1099.md#atomic-test-5---windows---modify-file-creation-timestamp-with-powershell) in T1099 Timestomp to use the executor powershell and not command_prompt which gives an error. 
This is the modification I made in T1099.yaml.
```
executor:
    name: powershell
    command: |
      Get-ChildItem #{file_path} | % { $_.LastWriteTime = '#{target_date_time}' }
```

## What did you expect to happen?
I expected the command to work and change the CreatrionTime of file C:\Some\file.txt

## What happened instead?
Powershell keeps waiting for stdin and subprocess.TimeoutExpired exception is raised.
 
## Your Environment
Tested in Win7 x32 and x64. In Win10 x64 works perfectly.

## Possible Solution
Changed line 315 in runner.py with `return [ "powershell.exe", "-"]` and the issue is fixed.
The parameter "-" in PowerShell is used to interpret redirected STDIN.
