### ISSUE TITLE
T1002 - Compress Data for Exfiltration With Rar fails 

### ISSUE THREAD

**Issue by maxverro** [redcanaryco/atomic-red-team#712]
This [PR](https://github.com/redcanaryco/atomic-red-team/pull/655) as introduced à bug.

The build is marked as success but the test will not run:
https://circleci.com/gh/redcanaryco/atomic-red-team/1790

To fix the issue, we simply need to add the variable symbol "#" before {file_extension} 
```
    executor:
      name: command_prompt
      elevation_required: false
      prereq_command: |
        rar /?
      command: |
        rar a -r #{output_file} #{input_path}*{file_extension}
```
Output from our test runner without the fix: 
```
Executing Test #2:  Windows Atomic Red Team :: Data Compressed (T1002) :: Compress Data for Exfiltration With Rar
rar a -r %USERPROFILE%\data.rar %USERPROFILE%*{file_extension} 
                                                ^ var is not replaced
```

Output from our test runner with the fix: 
```
Executing Test #2:  Windows Atomic Red Team :: Data Compressed (T1002) :: Compress Data for Exfiltration With Rar
rar a -r %USERPROFILE%\data.rar %USERPROFILE%*.txt

```

_Originally posted by @maxverro in https://github.com/redcanaryco/atomic-red-team/pull/655#issuecomment-563315466_
